export const DEFAULT_SETTINGS = Object.freeze({
  authType: "oauth",
  token: "",
  refreshToken: "",
  workspaceId: "",
  workspaceName: "",
  workspaceIcon: "",
  botId: "",
  connectionId: "",
  destinationType: "database",
  destinationId: "",
  destinationDatabaseId: "",
  destinationName: "Quick Notes",
  destinationUrl: "",
  titleProperty: "Name",
  managedDestination: false,
  destinationSchemaVersion: 0,
  destinationMarker: "",
  destinationProperties: {},
  destinationConnectionId: "",
  databaseProvisioning: null,
  onboardingComplete: false,
  includeSource: true,
  aiEnabled: true,
  aiSuggestTitle: true,
  aiExtractTodos: true,
  oauthClientId: "",
  oauthBrokerUrl: ""
});
